language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install:
  - "pip install tox"

script: tox

sudo: false

notifications:
  irc:
    channels:
      - "irc.freenode.net#boatd"
    template:
      - "%{repository}/%{branch} [%{commit}] %{author}: %{message}"
      - "Build #%{build_number}: %{build_url}"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
