language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install: "pip install -r requirements.txt"
script: nosetests
notifications:
  irc:
    channels:
      - "irc.freenode.net#boatd"
    template:
      - "%{repository}/%{branch} [%{commit}] %{author}: %{message}"
      - "Build #%{build_number}: %{build_url}"
    on_success: changed
    on_failure: always
    use_notice: true
    skip_join: true
